import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import styles from "../styles/layout.module.css";

export default function Layout ({ children }) {
  const [menuState, setMenuState] = useState("none");

  const openButtonHandler = () => {
    setMenuState("flex");
  }

  const closeButttonHandler = () => {
    setMenuState("none");
  }

  return (
    <div className={styles.widthContainer}>
      <div className={styles.container}>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <header className={styles.headerContainer}>
          <Link className={`${styles.firstLink} ${styles.link}`} href="/">Home</Link>
          <Link className={styles.link} href="/about">About</Link>
          <Link className={styles.link} href="/stack">Stack</Link>
          <Link className={styles.link} href="/projects">Projects</Link>

          <button className={styles.adaptiveOpen} onClick={openButtonHandler}>☰</button>
          <div className={styles.adaptiveMenu} style={{display: menuState}}>
            <button className={styles.adaptiveClose} onClick={closeButttonHandler}>×</button>
            <Link className={`${styles.firstLink} ${styles.link}`} href="/">Home</Link>
            <Link className={styles.link} href="/about">About</Link>
            <Link className={styles.link} href="/stack">Stack</Link>
            <Link className={styles.link} href="/projects">Projects</Link>
          </div>
        </header>
      </div>
      <main>{children}</main>
    </div>
  )
}